FROM alpine

RUN apk update && apk add git make gcc musl-dev

WORKDIR /usr/src/app

RUN git clone https://github.com/GektorPestarzt/MEPHI_parvpo.git/src

WORKDIR /usr/src/app/MEPHI_parvpo/lab1

RUN make parallel
CMD ["./parallel.out"]
