FROM nginx

RUN apt-get update && apt-get install -y build-essential git

WORKDIR /usr/src/app

RUN git clone https://github.com/GektorPestarzt/MEPHI_parvpo.git

WORKDIR /usr/src/app/MEPHI_parvpo/lab1

RUN make parallel
CMD ["./parallel.out"]

# CMD ["nginx", "-g", "daemon off;"]