FROM alpine

RUN apk update && apk add git make gcc musl-dev

WORKDIR /usr/src/app

RUN git clone https://github.com/GektorPestarzt/mephi_parvpo.git

WORKDIR /usr/src/app/mephi_parvpo/lab1/src

RUN make parallel
CMD ["./parallel.out"]
